/**:  # 通配符，表示所有节点都能看到下面的参数
  ros__parameters:
    q_init: 0.2
    timestep: 0.01
    duration: 40.0
    urdf_path: "~/ros2_ws/dynamic_ws/src/vi/urdf/7_pendulum.urdf"
    eps_diff: 1.0e-6

atsvi_ad_node:
  ros__parameters:
    h_min: 1e-6
    h_max: 0.1
    max_adapt_iters: 100

etsvi_node:
  ros__parameters:
    lyap_alpha: 0.
    lyap_beta: 0.04

etsvi_op_node:
  ros__parameters:
    pid_Kp: 0.0093
    pid_Ki: 1e-4
    pid_Kd: 1e-9